apiVersion: apps/v1
kind: Deployment
metadata:
  name: toxicity-api
  labels: { app: toxicity-api }
spec:
  replicas: 1
  selector:
    matchLabels: { app: toxicity-api }
  template:
    metadata:
      labels: { app: toxicity-api }
    spec:
      containers:
      - name: toxicity-api
        # L’image exacte sera injectée par cloudbuild 'kubectl set image'
        image: europe-west1-docker.pkg.dev/PROJECT_ID/toxicity/toxicity-api:placeholder
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: APP_SKIP_STARTUP
          value: "0"
        readinessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet: { path: /health, port: 8080 }
          initialDelaySeconds: 20
          periodSeconds: 20
        resources:
          requests: { cpu: "250m", memory: "512Mi" }
          limits:   { cpu: "1",    memory: "2Gi"   }
