apiVersion: v1
kind: Service
metadata:
  name: toxicity-api-svc
  namespace: toxicity
spec:
  type: LoadBalancer
  selector:
    app: toxicity-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
